# Common information for your repository
pom.groupId=io.github.ptitjes
pom.version=0.1.0-SNAPSHOT
pom.description=Syrup is fizzy mix of sweet-spi and kodein-di
pom.vcsUrl=https://github.com/ptitjes/syrup
pom.developer=Didier Villevalois
pom.license=ASL2.0

# Optional: configure compatibility
java.compatibility=21
kotlin.compatibility=2.3.0

# Optional: publish older versions of the Kdoc (requires them to be already published)
#kdoc.olderVersions=1.0.0,2.0.0
